services:
  Backoffice.Backend.courses.BackofficeCourseRepository:
    class: ../../../../../../Contexts/Backoffice/infrastructure/MongoBackofficeCourseRepository
    arguments: ['@Shared.ConnectionManager']

  Backoffice.Backend.courses.BackofficeCourseRepository2:
    class: ../../../../../../Contexts/Backoffice/infrastructure/ElasticBackofficeCourseRepository
    arguments: ['@Shared.ConnectionManagerElastic']

  Backoffice.Backend.courses.CoursesFinder:
    class: ../../../../../../Contexts/Backoffice/application/SearchAll/CoursesFinder
    arguments: ['@Backoffice.Backend.courses.BackofficeCourseRepository2']

  Backoffice.Backend.courses.SearchAllCoursesQueryHandler:
    class: ../../../../../../Contexts/Backoffice/application/SearchAll/SearchAllCoursesQueryHandler
    arguments: ['@Backoffice.Backend.courses.CoursesFinder']
    tags:
      - { name: 'queryHandler' }
