imports:
  - { resource: ./application.yaml }

services:
  Backoffice.Backend.EnvironmentArranger:
    class: ../../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@Shared.MongoConnectionManager']

  Backoffice.Backend.ElasticEnvironmentArranger:
    class: ../../../../../../tests/Contexts/Shared/infrastructure/elastic/ElasticEnvironmentArranger
    arguments: ['@Shared.ElasticConnectionManager']

  Shared.EventBus:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/InMemory/InMemorySyncEventBus
    arguments: []
